<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>BuildingBlocks.IntegrationEventLogEF</RootNamespace>
    <IsPublishable>false</IsPublishable>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Contracts\BuildingBlocks.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EntityFrameworkCore.Locking.PostgreSQL" Version="0.5.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

</Project>