<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-ArticlesOutboxWorker-4f3a829a-62aa-4269-97fc-47d24c189e27</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.15.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Configuration\BuildingBlocks.Configuration.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\IntegrationEventLogEF\BuildingBlocks.IntegrationEventLogEF.csproj" />
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Logging\BuildingBlocks.Logging.csproj" />
    <ProjectReference Include="..\..\Infrastructure\DataAccess\ArticlesService.Infrastructure.DataAccess.csproj" />
  </ItemGroup>
</Project>
