name: BUILD_AND_TEST

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore ArticlesApp.slnx

      - name: Create empty .env file
        run: touch .env

      - name: Build Solution
        run: dotnet build ArticlesApp.slnx --no-restore --configuration Release

      - name: Run All Tests
        run: dotnet test ArticlesApp.slnx --no-build --configuration Release --verbosity normal

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Articles API Docker image
        run: docker build -f ./src/Services/ArticlesService/ArticlesAPI/Dockerfile -t articles-api:${{ github.sha }} .

      - name: Build Articles Outbox Worker Docker image
        run: docker build -f ./src/Services/ArticlesService/ArticlesWorkers/ArticlesOutboxWorker/Dockerfile -t articles-outbox-worker:${{ github.sha }} .

      - name: Build Notification Service Docker image
        run: docker build -f ./src/Services/NotificationService/Dockerfile -t notification-service:${{ github.sha }} .
